package db

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/LambdaIITH/Dashboard/backend/config"
	"github.com/LambdaIITH/Dashboard/backend/internal/schema"
)

// create a new complaint and returns the complaintID generated by the DB
func CreateComplaint(ctx context.Context, userID int64, complaint *schema.HostelComplaintRequest) (int64, error) {
	complaintDataJSON, err := json.Marshal(complaint.ComplaintData)
	if err != nil {
		return 0, fmt.Errorf("failed marshaling the complaint data: %w", err)
	}

	query := `
		INSERT INTO hostel_complaints (user_id, complaint_description, complaint_data, complaint_status)
		VALUeS ($1, $2, $3, 'received')
		RETURNING id;
	`

	var complaintID int64
	err = config.DB.QueryRow(ctx, query, userID, complaint.ComplaintDescription, complaintDataJSON).Scan(&complaintID)
	if err != nil {
		return 0, fmt.Errorf("failed to create the complaint: %w", err)
	}

	return complaintID, nil
}

// To add the image urls for a complaint
func AddComplaintImages(ctx context.Context, complaintID int64, imageURLs []string) error {
	if len(imageURLs) == 0 {
		return nil
	}

	query := `INSERT INTO hostel_complaint_images (complaint_id, image_url) VALUES($1, $2);`

	for _, imageURL := range imageURLs {
		_, err := config.DB.Exec(ctx, query, complaintID, imageURL)
		if err != nil {
			return fmt.Errorf("failed to add image %w", err)
		}
	}
	return nil
}

// to fetch the images for the complaint
func GetComplaintImages(ctx context.Context, complaintID int64) ([]string, error) {
	query := `SELECT image_url FROM hostel_complaint_images WHERE complaint_id=$1;`

	rows, err := config.DB.Query(ctx, query, complaintID)
	if err != nil {
		return nil, fmt.Errorf("failed to get images :%w", err)
	}
	defer rows.Close()

	var images []string
	for rows.Next() {
		var imageURL string
		err := rows.Scan(&imageURL)
		if err != nil {
			return nil, fmt.Errorf("failed to scan image %w", err)
		}
		images = append(images, imageURL)
	}
	return images, nil
}

// get complaint by using the complaintID
func GetComplaintByID(ctx context.Context, id int64) (map[string]interface{}, error) {
	query := `
		SELECT hc.id, hc.user_id, hc.complaint_description, hc.complaint_data, hc.complaint_status, hc.created_at, hc.resolved_at, u.name, u.email
		FROM hostel_complaints AS hc
		INNER JOIN users AS u ON hc.user_id = u.id
		WHERE hc.id = $1;
	`

	var complaintID, userID int64
	var complaintDescription, complaintStatus, userName, userEmail string
	var complaintDataJSON []byte
	var createdAt interface{}
	var resolvedAt interface{}

	err := config.DB.QueryRow(ctx, query, id).Scan(&complaintID, &userID, &complaintDescription, &complaintDataJSON, &complaintStatus, &createdAt, &resolvedAt, &userName, &userEmail)
	if err != nil {
		return nil, fmt.Errorf("complaint not found: %w", err)
	}

	var complaintData map[string]interface{}
	if len(complaintDataJSON) > 0 {
		err = json.Unmarshal(complaintDataJSON, &complaintData)
		if err != nil {
			complaintData = make(map[string]interface{})
		}
	} else {
		complaintData = make(map[string]interface{})
	}

	//fetch imgaes
	images, err := GetComplaintImages(ctx, complaintID)
	if err != nil {
		return nil, fmt.Errorf("failed to get images: %w", err)
	}

	complaint := map[string]interface{}{
		"id":                    complaintID,
		"user_id":               userID,
		"complaint_description": complaintDescription,
		"complaint_data":        complaintData,
		"complaint_status":      complaintStatus,
		"created_at":            createdAt,
		"resolved_at":           resolvedAt,
		"user_name":             userName,
		"user_email":            userEmail,
		"images":                images,
	}

	return complaint, nil

}

// get users all complaints
func GetUserComplaints(ctx context.Context, userID int64) ([]map[string]interface{}, error) {
	query := `
		SELECT hc.id, hc.complaint_description, hc.complaint_data, hc.complaint_status, hc.created_at, hc.resolved_at
		FROM hostel_complaints AS hc
		where hc.user_id = $1
		ORDER BY hc.created_at DESC;
	`

	rows, err := config.DB.Query(ctx, query, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch user complaints: %w", err)
	}
	defer rows.Close()

	var complaints []map[string]interface{}

	for rows.Next() {
		var id int64
		var complaintDescription, complaintStatus string
		var complaintDataJSON []byte
		var createdAt interface{}
		var resolvedAt interface{}

		err := rows.Scan(&id, &complaintDescription, &complaintDataJSON, &complaintStatus, &createdAt, &resolvedAt)

		if err != nil {
			return nil, fmt.Errorf("failed to scan complaint: %w", err)
		}

		var complaintData map[string]interface{}
		if len(complaintDataJSON) > 0 {
			err = json.Unmarshal(complaintDataJSON, &complaintData)
			if err != nil {
				return nil, fmt.Errorf("failed to unmarshal complaint data : %w", err)
			}
		} else {
			complaintData = make(map[string]interface{})
		}

		//get images
		images, err := GetComplaintImages(ctx, id)
		if err != nil {
			return nil, fmt.Errorf("failed to get images for complaint : %w", err)
		}

		complaint := map[string]interface{}{
			"id":                    id,
			"complaint_description": complaintDescription,
			"complaint_data":        complaintData,
			"complaint_status":      complaintStatus,
			"created_at":            createdAt,
			"resolved_at":           resolvedAt,
			"images":                images,
		}

		complaints = append(complaints, complaint)

	}

	return complaints, nil
}
