package db

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"

	"github.com/LambdaIITH/Dashboard/backend/internal/schema"
)

// DBQueryer helps in transaction management
type DBQueryer interface {
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
}

// create a new complaint and returns the complaintID generated by the DB
func CreateComplaint(ctx context.Context, db DBQueryer, userID int64, complaint *schema.HostelComplaintRequest) (int64, error) {
	complaintDataJSON, err := json.Marshal(complaint.ComplaintData)
	if err != nil {
		return 0, fmt.Errorf("failed marshaling the complaint data: %w", err)
	}

	query := `
		INSERT INTO hostel_complaints (user_id, complaint_description, complaint_data, complaint_status, hostel, room_number)
		VALUES ($1, $2, $3, 'Pending', $4, $5)
		RETURNING id;
	`

	var complaintID int64
	err = db.QueryRow(ctx, query, userID, complaint.ComplaintDescription, complaintDataJSON, complaint.ResultHostel, complaint.ResultRoomNumber).Scan(&complaintID)
	if err != nil {
		return 0, fmt.Errorf("failed to create the complaint: %w", err)
	}

	return complaintID, nil
}

// To add the image urls for a complaint
func AddComplaintImages(ctx context.Context, db DBQueryer, complaintID int64, imageURLs []string) error {
	if len(imageURLs) == 0 {
		return nil
	}

	query := `INSERT INTO hostel_complaint_images (complaint_id, image_url) VALUES($1, $2);`

	for _, imageURL := range imageURLs {
		_, err := db.Exec(ctx, query, complaintID, imageURL)
		if err != nil {
			return fmt.Errorf("failed to add image %w", err)
		}
	}
	return nil
}

// to fetch the images for the complaint
func GetComplaintImages(ctx context.Context, db DBQueryer, complaintID int64) ([]string, error) {
	query := `SELECT image_url FROM hostel_complaint_images WHERE complaint_id=$1;`

	rows, err := db.Query(ctx, query, complaintID)
	if err != nil {
		return nil, fmt.Errorf("failed to get images :%w", err)
	}
	defer rows.Close()

	var images []string
	for rows.Next() {
		var imageURL string
		err := rows.Scan(&imageURL)
		if err != nil {
			return nil, fmt.Errorf("failed to scan image %w", err)
		}
		images = append(images, imageURL)
	}
	return images, nil
}

// get complaint by using the complaintID
func GetComplaintByID(ctx context.Context, db DBQueryer, id int64) (map[string]interface{}, error) {
	query := `
		SELECT hc.id, hc.user_id, hc.complaint_description, hc.complaint_data, hc.complaint_status, hc.created_at, hc.resolved_at, hc.hostel, hc.room_number, u.name, u.email
		FROM hostel_complaints AS hc
		INNER JOIN users AS u ON hc.user_id = u.id
		WHERE hc.id = $1;
	`

	var complaintID, userID int64
	var complaintDescription, complaintStatus, userName, userEmail string
	var hostel, roomNumber *string
	var complaintDataJSON []byte
	var createdAt time.Time
	var resolvedAt interface{}

	err := db.QueryRow(ctx, query, id).Scan(&complaintID, &userID, &complaintDescription, &complaintDataJSON, &complaintStatus, &createdAt, &resolvedAt, &hostel, &roomNumber, &userName, &userEmail)
	if err != nil {
		return nil, fmt.Errorf("complaint not found: %w", err)
	}

	var complaintData map[string]interface{}
	if len(complaintDataJSON) > 0 {
		err = json.Unmarshal(complaintDataJSON, &complaintData)
		if err != nil {
			complaintData = make(map[string]interface{})
		}
	} else {
		complaintData = make(map[string]interface{})
	}

	//fetch imgaes
	images, err := GetComplaintImages(ctx, db, complaintID)
	if err != nil {
		return nil, fmt.Errorf("failed to get images: %w", err)
	}

	complaint := map[string]interface{}{
		"id":                    complaintID,
		"user_id":               userID,
		"complaint_description": complaintDescription,
		"complaint_data":        complaintData,
		"complaint_status":      complaintStatus,
		"created_at":            createdAt,
		"resolved_at":           resolvedAt,
		"user_name":             userName,
		"user_email":            userEmail,
		"images":                images,
		"hostel":                "",
		"room_number":           "",
	}

	if hostel != nil {
		complaint["hostel"] = *hostel
	}
	if roomNumber != nil {
		complaint["room_number"] = *roomNumber
	}

	return complaint, nil

}

// get users all complaints
func GetUserComplaints(ctx context.Context, db DBQueryer, userID int64) ([]map[string]interface{}, error) {
	query := `
		SELECT hc.id, hc.complaint_description, hc.complaint_data, hc.complaint_status, hc.created_at, hc.resolved_at, hc.hostel, hc.room_number
		FROM hostel_complaints AS hc
		WHERE hc.user_id = $1
		ORDER BY hc.created_at DESC;
	`

	rows, err := db.Query(ctx, query, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch user complaints: %w", err)
	}
	defer rows.Close()

	var complaints []map[string]interface{}

	for rows.Next() {
		var id int64
		var complaintDescription, complaintStatus string
		var hostel, roomNumber *string
		var complaintDataJSON []byte
		var createdAt interface{}
		var resolvedAt interface{}

		err := rows.Scan(&id, &complaintDescription, &complaintDataJSON, &complaintStatus, &createdAt, &resolvedAt, &hostel, &roomNumber)

		if err != nil {
			return nil, fmt.Errorf("failed to scan complaint: %w", err)
		}

		var complaintData map[string]interface{}
		if len(complaintDataJSON) > 0 {
			err = json.Unmarshal(complaintDataJSON, &complaintData)
			if err != nil {
				return nil, fmt.Errorf("failed to unmarshal complaint data : %w", err)
			}
		} else {
			complaintData = make(map[string]interface{})
		}

		//get images
		images, err := GetComplaintImages(ctx, db, id)
		if err != nil {
			return nil, fmt.Errorf("failed to get images for complaint : %w", err)
		}

		complaint := map[string]interface{}{
			"id":                    id,
			"complaint_description": complaintDescription,
			"complaint_data":        complaintData,
			"complaint_status":      complaintStatus,
			"created_at":            createdAt,
			"resolved_at":           resolvedAt,
			"images":                images,
			"hostel":                "",
			"room_number":           "",
		}

		if hostel != nil {
			complaint["hostel"] = *hostel
		}
		if roomNumber != nil {
			complaint["room_number"] = *roomNumber
		}

		complaints = append(complaints, complaint)

	}

	return complaints, nil
}

func UpdateComplaintStatus(ctx context.Context, db DBQueryer, complaintID int64, status string) error {
	query := `
	UPDATE hostel_complaints
	SET complaint_status = $2::text,
		resolved_at = CASE
			WHEN LOWER($2::text) IN ('resolved', 'closed') THEN CURRENT_TIMESTAMP
			ELSE NULL
		END
	WHERE id = $1;
	`

	tag, err := db.Exec(ctx, query, complaintID, status)
	if err != nil {
		return fmt.Errorf("failed to update the complaint status: %w", err)
	}

	if tag.RowsAffected() == 0 {
		return fmt.Errorf("complaint not found")
	}
	return nil
}

// sets is_sheet_synced to true
func MarkComplaintAsSynced(ctx context.Context, db DBQueryer, complaintID int64) error {
	query := `
		UPDATE hostel_complaints
		SET is_sheet_synced = TRUE
		WHERE id = $1;
	`
	_, err := db.Exec(ctx, query, complaintID)
	return err
}

//increments the sync attempt counter
func IncrementSyncAttempts(ctx context.Context, db DBQueryer, complaintID int64) error {
	query := `
		UPDATE hostel_complaints
		SET sheet_sync_attempts = sheet_sync_attempts + 1
		WHERE id = $1;
	`
	_, err := db.Exec(ctx, query, complaintID)
	return err
}

// fetches complaints that haven't been synced to the sheet yet ignoring complaint with >=10 fails
func GetUnsyncedComplaints(ctx context.Context, db DBQueryer) ([]map[string]interface{}, error) {
	query := `
		SELECT hc.id, hc.user_id, hc.complaint_description, hc.complaint_data, hc.complaint_status, hc.created_at, hc.resolved_at, hc.sheet_sync_attempts, hc.hostel, hc.room_number, u.name, u.email, u.phone_number
		FROM hostel_complaints AS hc
		INNER JOIN users AS u ON hc.user_id = u.id
		WHERE hc.is_sheet_synced = FALSE AND hc.sheet_sync_attempts < 10
		ORDER BY hc.id ASC;
	`

	rows, err := db.Query(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch unsynced complaints: %w", err)
	}
	defer rows.Close()

	var complaints []map[string]interface{}
	
	for rows.Next() {
		var complaintID, userID int64
		var complaintDescription, complaintStatus, userName, userEmail string
		var userPhone *string 
		var hostel, roomNumber *string
		var complaintDataJSON []byte
		var createdAt time.Time
		var resolvedAt interface{}
		var syncAttempts int

		err := rows.Scan(&complaintID, &userID, &complaintDescription, &complaintDataJSON, &complaintStatus, &createdAt, &resolvedAt, &syncAttempts, &hostel, &roomNumber, &userName, &userEmail, &userPhone)
		if err != nil {
			return nil, fmt.Errorf("failed to scan complaint: %w", err)
		}

		var complaintData map[string]interface{}
		if len(complaintDataJSON) > 0 {
			if err := json.Unmarshal(complaintDataJSON, &complaintData); err != nil {
				fmt.Printf("Error unmarshaling complaint data for ID %d: %v\n", complaintID, err)
				complaintData = make(map[string]interface{})
			}
		} else {
			complaintData = make(map[string]interface{})
		}
		
		phone := ""
		if userPhone != nil {
			phone = *userPhone
		}

		//fetch images
		images, err := GetComplaintImages(ctx, db, complaintID)
		if err != nil {
			fmt.Printf("Error fetching images for complaint %d: %v\n", complaintID, err)
			images = []string{}
		}

		complaint := map[string]interface{}{
			"id":                    complaintID,
			"user_id":               userID,
			"complaint_description": complaintDescription,
			"complaint_data":        complaintData,
			"complaint_status":      complaintStatus,
			"created_at":            createdAt,
			"resolved_at":           resolvedAt,
			"user_name":             userName,
			"user_email":            userEmail,
			"user_phone":            phone,
			"images":                images,
			"sheet_sync_attempts":   syncAttempts,
			"hostel":                "",
			"room_number":           "",
		}
		
		if hostel != nil {
			complaint["hostel"] = *hostel
		}
		if roomNumber != nil {
			complaint["room_number"] = *roomNumber
		}
		
		if strings.Contains(userEmail, "@") {
			parts := strings.Split(userEmail, "@")
			complaint["user_roll_no"] = parts[0]
		}
		
		complaints = append(complaints, complaint)
	}
	
	return complaints, nil
}
