// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGwHvbCTCmmZHI1AG_2LW62zIGZl_eAEo',
    appId: '1:472121739465:web:c209e655440be93f9d6518',
    messagingSenderId: '472121739465',
    projectId: 'dashboard-iith',
    authDomain: 'dashboard-iith.firebaseapp.com',
    storageBucket: 'dashboard-iith.appspot.com',
    measurementId: 'G-H0YXVRV2BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1yUytVpk3j4kIIOGXgW3_3cEMm0OaUo0',
    appId: '1:472121739465:android:e7080caa6f17001e9d6518',
    messagingSenderId: '472121739465',
    projectId: 'dashboard-iith',
    storageBucket: 'dashboard-iith.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF6912XrlY_LAEws85ddea2Xgp2-_cjV8',
    appId: '1:472121739465:ios:8a4d7185dde781269d6518',
    messagingSenderId: '472121739465',
    projectId: 'dashboard-iith',
    storageBucket: 'dashboard-iith.appspot.com',
    iosBundleId: 'dev.iith.dashboard.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF6912XrlY_LAEws85ddea2Xgp2-_cjV8',
    appId: '1:472121739465:ios:8a4d7185dde781269d6518',
    messagingSenderId: '472121739465',
    projectId: 'dashboard-iith',
    storageBucket: 'dashboard-iith.appspot.com',
    iosBundleId: 'dev.iith.dashboard.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGwHvbCTCmmZHI1AG_2LW62zIGZl_eAEo',
    appId: '1:472121739465:web:28e3fd4ec06b8a3f9d6518',
    messagingSenderId: '472121739465',
    projectId: 'dashboard-iith',
    authDomain: 'dashboard-iith.firebaseapp.com',
    storageBucket: 'dashboard-iith.appspot.com',
    measurementId: 'G-32K0B7S4PL',
  );
}
